### ISSUE TITLE
Implement Scenario11 with 2-state Markov model for traffic arrival

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coordination-simulation#104]
Basically switch between state wit high and low traffic arrival (different inter-arrival means). The transition between the states should be configurable and slow enough for the agent to have multiple decisions in between.

Best to first read a bit on MMP and then propose an idea on how to implement it in the simulator and how to design the scenario.

![image](https://user-images.githubusercontent.com/28340802/66304173-e7362a00-e8fc-11e9-8041-5443592c12cf.png)

**Comment by stefanbschneider** [comment]
As you suggested, it's fine to first create another scenario with traces where load goes up and down and up and down. So that we can start testing quickly with that one.

But then we should create a new scenario using this MMP to achieve unpredictable traffic for the agent.

**Comment by stefanbschneider** [comment]
@qarawlus Could you please actively check and confirm that when running multiple episodes with the simulator and a given seed, the different episodes are not identical?

I'm a bit afraid that the seeding in the simulator init at the beginning of each episode leads to exactly the same "random" behavior in each episode (here, regarding state switches).
We would want really random, different behavior in different episodes.

**Comment by qarawlus** [comment]
The seed for the simulator is generated using the seed given to the agent using a different random generator inside. So the seed that is passed to the simulator with every `init` call is different than the seed of the agent. Using the seed param for the agent will only make the internal agent seed generator generate the same seeds for the simulator. 

See here: https://github.com/RealVNF/rl-coordination/blob/master/src/rlsp/envs/scale_and_place_simulated.py#L75

**Comment by stefanbschneider** [comment]
Ok, I guess this works
