### ISSUE TITLE
Double headers in .csv files

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coordination-simulation#122]
I get two headers at the beginning of the CSV files: https://github.com/RealVNF/evaluation/blob/master/BJointSPvsRL/RL-DDPG/abilene-in4-cap1/abc/det-arrival10_det-size001_duration100_100k-train/best/2020-01-07_16-39-29_seed4567/test-2020-01-09_08-20-30/placements.csv#L1

Both simulator and RL are up to date.

**Comment by stefanbschneider** [comment]
This was causing wrong behavior in the eval notebook when reading the placements, so I manually removed the double heading for `placement.csv`. It's still there for the other `.csv` files (not sure why it doesn't cause problems there).

Related to https://github.com/RealVNF/evaluation/issues/29

**Comment by qarawlus** [comment]
Fixed in https://github.com/RealVNF/rl-coordination/pull/156
