### ISSUE TITLE
Writing placement statistics

### ISSUE THREAD

**Issue by qarawlus** [RealVNF/coordination-simulation#59]
The simulator should be able to record statistics about placement decisions. 

As a start, the placements of the SFs should be recorded to a results file.

**Comment by qarawlus** [comment]
Next step would be documenting the scheduling rules., identifying which node gets the highest load.

**Comment by stefanbschneider** [comment]
Yep, plus recording additional metrics like total VNFs, resource consumption, delays, successful and dropped flows etc.

Probably best to write these into three different CSV files for placement, schedule, and additonal metrics, respectively. What do you think?

**Comment by qarawlus** [comment]
Yes, definitely will write to multiple files. Will work on those and update. Hopefully it will not be a lot of overhead to finish. 
For resource consumption and the other numerical metrics, should I record them at each interval (e.g. node 1 at time 1000 has 8/10 load, at time 2000, 5/10) so that we can create time based charts? If not, how should I record them?

**Comment by stefanbschneider** [comment]
Yes, I'd record them at the fixed interval at the same time when you get actions from the agent and then return the state.
