### ISSUE TITLE
Remove empty lines in generate CSV files

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coordination-simulation#64]
Generated CSV files for placement etc always have blank lines in between:

```
time,node,sf

0,pop0,b

0,pop0,c

0,pop0,a
```

Very low priority, but if easy & fast to fix it would be nice to get rid of them. Else just keep issue open for now

**Comment by qarawlus** [comment]
I tested this on windows and linux and was not able to reproduce it. On which platform was this recorded?

**Comment by svenuthe** [comment]
smells like a line ending line feed platform issue

**Comment by qarawlus** [comment]
Fixed in latest merge. As Sven said, it was indeed a Windows issue, the files generated using the windows CSV version add endings to lines in a weird order that confuses the system.
