### ISSUE TITLE
Record max resource usage per node per run

### ISSUE THREAD

**Issue by qarawlus** [RealVNF/coordination-simulation#77]
We are currently losing flow and traffic information in the simulator that happen in the period between the interactions of outside algorithms with the simulator interface. We should agree on a method to keep that data because the current method of reporting only the data at specific points while ignoring the ones in between is incorrect. 

The solution of reducing the period in which the simulator runs before asking for decision introduces overhead for non simple scenarios. This is due to many changes happening in the simulator environment in addition to having outside algorithms (RL agent for example) calculate placement and schedule every time for that small duration. 

The solution to this issue should allow for long duration before asking for decisions, while still maintaining accurate traffic data for the duration that preceded the moment a decision was requested.

**Comment by stefanbschneider** [comment]
What do you mean exactly? When we have `run_duration=x`, that at a time t where interaction between agent and simulator happens, we only get instantaneous simulator observations at time t and not summarized over the whole duration between t-x and t?

What additional information would you want to have? The flow counters and average delays account for the whole interval already. Only the resource consumption is instantaneous and not averaged.

**Comment by stefanbschneider** [comment]
Ok, we also have the issue with traffic, which is only recorded instantaneously. If we had the average or aggregate traffic during a run, we could use this info to compute a placement more easily. See https://github.com/RealVNF/rl-coordination/pull/45

**Comment by qarawlus** [comment]
It's exactly why I created this issue. We are losing important information that occur in between the the decision moments. I am still thinking of way of how we can store that information without having to change a lot of stuff (both RL and Simulator side). 
Initially, I had the idea of storing all flows and flow events in a dictionary and add time as well, but that would require a lot of rework from the RL side. Also averaging the traffic information over that period is also a solution, but it leaves us with a less accurate representation of what happened.

**Comment by stefanbschneider** [comment]
We addressed this for traffic by just aggregating all traffic over one run. 

We still have the issue with node load, which is currently just the instantaneous load at the end of a run. Probably makes sense to keep track of the maximum used resources per node in each run and use that to calculate the max load per run.

Not crucial for previous scenarios but should be useful for scenarios with stochastic and dynamic traffic (Scenairo08 and 09).
