### ISSUE TITLE
Record the location of dropped flows in the network

### ISSUE THREAD

**Issue by qarawlus** [RealVNF/coordination-simulation#99]
The simulator does not currently record where flows are dropped in the network, it just records metrics of total dropped flows. 

The simulator should be able to record at which nodes the flows are dropped in addition to recording the total number of dropped flows.

**Comment by stefanbschneider** [comment]
I think this would be useful for evaluation and relatively low effort to implement.

I'd simply add a dict with key: tuple `(node_id, sf_id)` and value a simple counter that starts at 0 and is incremented whenever a flow is dropped at `node_id` going to/trying to use `sf_id`. At the end of simulation, just dump the dict as yaml file.
